version: '3.7'

services:
  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "6379:6379"
    networks:
      - ratelimit

  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goapp
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - ratelimit
    depends_on:
      redis:
        condition: service_healthy

networks:
  ratelimit:
    driver: bridge
